# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '3'
services:
  # mariadb:
  #   image: docker.io/bitnami/mariadb:11.1
  #   ports:
  #     - '3306:3306'
  #   environment:
  #     # ALLOW_EMPTY_PASSWORD is recommended only for development.
  #     - ALLOW_EMPTY_PASSWORD=no
  #     - MARIADB_USER=bn_moodle
  #     - MARIADB_PASSWORD=gfgdrgfd565457
  #     - MARIADB_ROOT_PASSWORD=gffdgrdfg443
  #     - MARIADB_DATABASE=bitnami_moodle
  #     - MARIADB_CHARACTER_SET=utf8mb4
  #     - MARIADB_COLLATE=utf8mb4_unicode_ci
  #     - MARIADB_ROOT_HOST="%"
  #   healthcheck:
  #     test: ['CMD', '/opt/bitnami/scripts/mariadb/healthcheck.sh']
  #     interval: 15s
  #     timeout: 5s
  #     retries: 6

#    volumes:
#      - 'mariadb_data:/bitnami/mariadb'
  moodle:
    image: docker.io/bitnami/moodle:latest
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - BITNAMI_DEBUG=true
      - MOODLE_DATABASE_HOST=moodledb20402.mysql.database.azure.com
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=dbadmin
      - MOODLE_DATABASE_PASSWORD=f4fGDsgr4332
      - MOODLE_DATABASE_ROOT_PASSWORD=f4fGDsgr4332
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - MOODLE_SITE_NAME=Learning Buddy
      - MOODLE_USERNAME=shailen
      - MOODLE_PASSWORD=exam123
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=no
      - MOODLE_DATABASE_TYPE=mysqli
#    volumes:
#      - 'moodle_data:/bitnami/moodle'
#      - 'moodledata_data:/bitnami/moodledata'
    # depends_on:
    #   - mariadb
# volumes:
#  mariadb_data:
#  moodle_data:
#  moodledata_data:

# volumes:
#   mariadb_data:
#       driver: azure_file
#       driver_opts:
#           share_name: moodleshare
#           storage_account_name: moodlestorage16194
#           storage_account_key: 4H7F+GL7cTf79SImxFf0HNiAExQGt4SdIm73bdYoMevmOIdE/zHwFpkTnN3u5H6dwXdkXYGMryUq+AStnHVIWA==
#   moodle_data:
#       driver: azure_file
#       driver_opts:
#           share_name: moodleshare
#           storage_account_name: moodlestorage16194
#           storage_account_key: 4H7F+GL7cTf79SImxFf0HNiAExQGt4SdIm73bdYoMevmOIdE/zHwFpkTnN3u5H6dwXdkXYGMryUq+AStnHVIWA==  
#   moodledata_data:
#       driver: azure_file
#       driver_opts:
#           share_name: moodleshare
#           storage_account_name: moodlestorage16194
#           storage_account_key: 4H7F+GL7cTf79SImxFf0HNiAExQGt4SdIm73bdYoMevmOIdE/zHwFpkTnN3u5H6dwXdkXYGMryUq+AStnHVIWA==